COUNTRY_CODES = {
    "australia": "AU",
    "botswana": "BW",
    "canada ": "CA",
    "ethiopia": "ET",
    "ghana": "GH",
    "india ": "IN",
    "indonesia": "ID",
    "ireland": "IE",
    "israel ": "IL",
    "kenya": "KE",
    "latvia": "LV",
    "malaysia": "MY",
    "namibia": "NA",
    "new_zealand": "NZ",
    "nigeria": "NG",
    "pakistan": "PK",
    "philippines": "PH",
    "singapore": "SG",
    "south_africa": "ZA",
    "tanzania": "TZ",
    "uganda": "UG",
    "united_kingdom": "GB",
    "united_states": "US",
    "zimbabwe": "ZW",
}
