"""add last_password_reset_token to users

Revision ID: 96a7793c98a3
Revises: 39de48d224af
Create Date: 2026-03-21 11:22:16.626499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a7793c98a3'
down_revision = '39de48d224af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_password_reset_token', sa.Text(), nullable=True))

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_password_reset_token')

    # ### end Alembic commands ###
