"""Added total_value field to Transaction table

Revision ID: ba60b9bac3a6
Revises: 7f7adebefe8c
Create Date: 2024-09-05 18:30:30.180498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba60b9bac3a6'
down_revision = '7f7adebefe8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_value', sa.Float(), nullable=False))

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('total_value')

    # ### end Alembic commands ###
