"""First migration

Revision ID: ec2542f2bf29
Revises: 
Create Date: 2024-09-10 21:06:34.901293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2542f2bf29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
